name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: 22.20.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: latest

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install
        run: pnpm install

      - name: Core Build
        run: pnpm run build:core

      - name: class-validator Build
        run: pnpm run build:class-validator

      - name: Yup Build
        run: pnpm run build:yup

      - name: Test
        run: pnpm run test
